name: build-docs

on:
  push:
    branches:
      - master

jobs:
  docs:
    if: github.repository == 'jellyfin/jellyfin-roku'
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.JF_BOT_TOKEN }}
      - name: Install NPM dependencies
        run: npm ci
      - name: Build API docs
        # TODO: fix jsdoc build errors then remove '|| true' from run command below
        run: npm run docs || true
      - name: Commit any changes back to the unstable branch
        uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5
        with:
          commit_message: Update API docs
          # use jellyfin-bot to commit the changes instead of the default github-actions[bot]
          commit_user_name: jellyfin-bot
          commit_user_email: team@jellyfin.org
          # use jellyfin-bot to author the changes instead of the default author of the merge commit
          commit_author: jellyfin-bot <team@jellyfin.org>
