name: build
on:
  pull_request:
  push:
    paths-ignore:
      - 'locale/**'
jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
      - uses: actions/setup-node@8c91899e586c5b171469028077307d293428b516 # tag=v3
        with:
          node-version: "14.12.0"
      - run: npm ci
      - run: npx ropm install
      - run: make dev
      - uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3
        with:
          name: Jellyfin-Roku-dev-${{ github.sha }}
          path: ${{ github.workspace }}/out/staging
          if-no-files-found: error
