name: roku-analysis

on:
  pull_request:

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  static:
    # don't run job on forks and prevent job from running twice when a PR pushes a new commit
    if: github.repository == 'jellyfin/jellyfin-roku' && github.event_name != 'pull_request' || github.repository == 'jellyfin/jellyfin-roku' && github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
        with:
          node-version: "lts/*"
          cache: "npm"
      - name: NPM install
        run: npm ci
      - name: Install roku module dependencies
        run: npm run ropm
      - name: Build dev app
        if: env.BRANCH_NAME != 'master'
        run: npm run build
      - name: Build app for production
        if: env.BRANCH_NAME == 'master'
        run: npm run build-prod
      - name: Setup Java
        uses: actions/setup-java@2dfa2011c5b2a0f1489bf9e433881c92c1631f88 # v4
        with:
          distribution: "temurin"
          java-version: "21"
      - name: Download the Static Channel Analysis CLI
        run: |
          curl -sSL "https://devtools.web.roku.com/static-channel-analysis/sca-cmd.zip" -o sca-cmd.zip
          unzip sca-cmd.zip
      - name: Run Roku Static Analysis
        run: ./sca-cmd/bin/sca-cmd ${{ github.workspace }}/build/staging --exit error
